llm:
  #api_type: "groq"
  model: "llama3-70b-8192"  # or gpt-3.5-turbo-1106 / gpt-4-1106-previewgit
  base_url: "https://api.groq.com/openai/v1"  # or forward url / other llm url
  api_key: "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"
repair_llm_output: true

mermaid:
  engine: "nodejs"
  path: "mmdc"
  puppeteer_config: "/app/metagpt/config/puppeteer-config.json"
  pyppeteer_path: "/usr/bin/chromium"
