services:
  opendevin-app:
    image: ghcr.io/opendevin/opendevin:0.6.2
    container_name: opendevin-app-${DATE}
    environment:
      - SANDBOX_USER_ID=${SANDBOX_USER_ID}
      - PERSIST_SANDBOX=true
      - SSH_PASSWORD=${SSH_PASSWORD}
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE}
    volumes:
      - ${WORKSPACE_BASE}:/opt/workspace_base
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    pull_policy: always
    restart: no